variables:
  majorVersion: 1
  minorVersion: 13
  
name: 'FollowMe_$(majorVersion).$(minorVersion).$(Build.BuildId)'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $file = '$(Build.SourcesDirectory)/FollowMe.toc'
      $rawVersion = '$(Build.BuildNumber)'
      $newVersion =$rawVersion.Remove(0,9)
      $filecontent = Get-Content $file
      $filecontent -replace '(^## Version: .*\.).*',"## Version: $newVersion" | Set-Content $(Build.BinariesDirectory)/FollowMe/FollowMe.toc

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.BinariesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)